### ISSUE TITLE
Proposal: remove logic for getting OAuth token

### ISSUE THREAD

**Issue by aeden** [dnsimple/dnsimple-go#15]
Should we remove the OAuth token acquisition logic from the core library and delegate OAuth token retrieval to a third-party library like https://godoc.org/golang.org/x/oauth2 as it handles things like refresh tokens, password credentials token, etc.?

**Comment by weppos** [comment]
FYI we will not likely support refresh tokens, nor the password credentials token. We only support the [Code grant flow](http://tools.ietf.org/html/rfc6749#section-4.1).

Therefore, the OAuth2 lib may be overkill. I see a value to provide a simple implementation that covers what we offer in our API, since we will likely also have something similar in other clients.

I'll take a look at the OAuth2.
